routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/test', 'HomeController@test')->name('test');

Route::get('/', 'GuestController@index')->name('index');
Route::get('/home', 'HomeController@index')->name('home');

//Teacher
Route::get('/teacher', 'TeacherController@index')->name('teacher');
Route::get('/teacher/register', 'TeacherController@register')->name('teacher.register');
Route::delete('/teacher/delete/{id}', 'TeacherController@destroy')->name('teacher.destroy');

Route::get('/profile', 'ProfileController@edit')->name('profile');
Route::post('/profile', 'ProfileController@update');
Route::resource('/news', 'NewsController');
Route::post('/child/confirm/{id}', 'GroupController@addChildren')->name('child.confirm');
Route::delete('/child/remove', 'GroupController@removeChildren')->name('child.remove');
Route::resource('/child', 'ChildController');
Route::resource('/group', 'GroupController');
Route::resource('/plan', 'PlanController');
Route::resource('/meal', 'MealController');
Route::resource('/product', 'ProductController');
Route::resource('/message', 'MessageController', ['only' => ['store', 'destroy']]);
Route::get('/diary', 'DiaryController@index')->name('diary.home');
Route::resource('/absence', 'AbsenceController');

Route::get('/cart', 'CartController@index');
Route::post('cart/add', 'CartController@add')->name('cart.add');
Route::delete('cart/{id}/delete', 'CartController@destroy')->name('cart.destroy');
Route::delete('cart/delete/all', 'CartController@deleteAll')->name('cart.destroy.all');
Route::post('/checkout', 'OrderController@checkout')->name('checkout');
Route::get('/payment-success', 'OrderController@paymentSuccess')->name('payment.success');
Route::get('/invoice', 'OrderController@invoice')->name('invoice');
Route::delete('subscription/stop/{id}', 'ProductController@stopSubscription')->name('subscription.stop');

app/Meal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meal extends Model {

}

app/Http/Controllers/MealController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Meal;

class MealController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $meals = Meal::orderBy('week', 'DESC')->get();

        return view('teacher.meal.index')->withMeals($meals);
    }

    public function create() {
        $daysEn = ['monday', 'tuesday', 'wednessday', 'thursday', 'friday'];
        $daysHu = ['Hétfő', 'Kedd', 'Szerda', 'Csütörtök', 'Péntek'];

        return view('teacher.meal.create')
                ->withDaysEn($daysEn)
                ->withDaysHu($daysHu);
    }

    public function store(Request $request) {

        $meal = new Meal;
        $meal->week = $request->input('week');

        $meal->monday_breakfast = $request->input('monday-breakfast') ?? "-";
        $meal->monday_lunch = $request->input('monday-lunch') ?? "-";
        $meal->monday_dinner = $request->input('monday-dinner') ?? "-";

        $meal->tuesday_breakfast = $request->input('tuesday-breakfast') ?? "-";
        $meal->tuesday_lunch = $request->input('tuesday-lunch') ?? "-";
        $meal->tuesday_dinner = $request->input('tuesday-dinner') ?? "-";

        $meal->wednessday_breakfast = $request->input('wednessday-breakfast') ?? "-";
        $meal->wednessday_lunch = $request->input('wednessday-lunch') ?? "-";
        $meal->wednessday_dinner = $request->input('wednessday-dinner') ?? "-";

        $meal->thursday_breakfast = $request->input('thursday-breakfast') ?? "-";
        $meal->thursday_lunch = $request->input('thursday-lunch') ?? "-";
        $meal->thursday_dinner = $request->input('thursday-dinner') ?? "-";

        $meal->friday_breakfast = $request->input('friday-breakfast') ?? "-";
        $meal->friday_lunch = $request->input('friday-lunch') ?? "-";
        $meal->friday_dinner = $request->input('friday-dinner') ?? "-";

        $meal->save();

        return redirect()->route('meal.index');
    }

    public function destroy($id) {
        $meal = Meal::find($id);
        $meal->delete();
        return redirect()->route('meal.index');
    }

}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class TeacherController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $teachers = User::where('type', 0)
                            ->orderBy('id', 'DESC')->paginate(30);


        return view('user.teacher.index')->withTeachers($teachers);;
    }

    public function register() {
        return view('user.teacher.register');
    }

    public function destroy($id) {
        $user = User::find($id);
        $user->delete();
        return redirect()->route('teacher');
    }

}

resources/views/teacher/meal/create.blade.php
@extends('layouts.app')

@section('styles')
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
@endsection

@section('content')
<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <div class="card">
                <div class="card-header">Menu létrehozása</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('meal.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="week" class="col-md-2 col-form-label text-md-right">Hét sorszáma</label>

                            <div class="col-md-6">
                                <input id="week" type="number" class="form-control @error('week') is-invalid @enderror" name="week" value="{{ old('week') }}" autocomplete="title" autofocus required>

                                @error('week')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <hr>

                        @foreach ($daysEn as $day)
                        <h5>{{ $daysHu[$loop->index] }}</h5>
                        <div class="form-group row">
                            <label for="title" class="col-md-2 col-form-label text-md-right">Reggeli</label>

                            <div class="col-md-6">
                                <input id="{{ $day}}-breakfast" type="text" class="form-control @error($day. 'breakfast') is-invalid @enderror"
                                name="{{ $day }}-breakfast" value="{{ old($day. '-breakfast') }}"
                                autofocus required>

                                @error('{{ $day}}-breakfast')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="title" class="col-md-2 col-form-label text-md-right">Ebéd</label>

                            <div class="col-md-6">
                                <input id="{{ $day}}-lunch" type="text" class="form-control @error($day. '-lunch') is-invalid @enderror"
                                name="{{ $day }}-lunch" value="{{ old($day. '-lunch') }}"
                                autofocus required>

                                @error('{{ $day}}-lunch')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="title" class="col-md-2 col-form-label text-md-right">Uzsonna</label>

                            <div class="col-md-6">
                                <input id="{{ $day}}-dinner" type="text" class="form-control @error($day. '-dinner') is-invalid @enderror"
                                name="{{ $day }}-dinner" value="{{ old($day. '-dinner') }}"
                                autofocus required>

                                @error('{{ $day}}-dinner')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <hr>
                        @endforeach

                        <div class="form-group row justify-content-center text-center mt-3 mb-0">
                            <button type="submit" class="btn btn-primary" id="btn-save">Mentés</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/teacher/meal/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container pb-4">

        <div class="row border-bottom border-1 border-dark my-4 pb-2 justify-content-between">
            <h5 class="font-bold mt-3 mb-0">
                Heti menük:
            </h5>
            @if(Auth::user()->type == 0)
            <a href="/meal/create" class="btn btn-primary btn-sm float-right mt-1 mr-1 mb-1">Hozzáad</a>
            @endif
        </div>

        <div class="d-flex mx-0 my-4 pb-3" style="overflow-x: scroll; min-height: 500px;">

            @if (count($meals) > 0)
                @foreach($meals as $meal)
                    <div class="card mx-2" style="min-width: 400px;">
                        <div class="d-flex card-header justify-content-between">
                            <h4 class="mb-0">{{ $meal->week }}. heti menu</h4>
                            @if(Auth::user()->type == 0)
                            <div class="row">
                                <form action="{{ route('meal.destroy', $meal->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    {{method_field('DELETE')}}
                                    <button onclick="return confirm('Biztos, hogy törölni szeretnéd a {{ $meal->week }}. heti menut?');" type="submit" class="btn btn-danger btn-sm mr-1"><i class="fas fa-trash"></i></button>
                                </form>
                            </div>
                            @endif
                        </div>
                        <div class="card-body">
                            <h5>Hétfő:</h5>
                            <p class="ml-3 mb-0">Reggeli: {{ $meal->monday_breakfast }}</p>
                            <p class="ml-3 mb-0">Ebéd: {{ $meal->monday_lunch }}</p>
                            <p class="ml-3 mb-0">Uzsonna: {{ $meal->monday_dinner }}</p>
                            <hr>
                            <h5>Kedd:</h5>
                            <p class="ml-3 mb-0">Reggeli: {{ $meal->tuesday_breakfast }}</p>
                            <p class="ml-3 mb-0">Ebéd: {{ $meal->tuesday_lunch }}</p>
                            <p class="ml-3 mb-0">Uzsonna: {{ $meal->tuesday_dinner }}</p>
                            <hr>
                            <h5>Szerda:</h5>
                            <p class="ml-3 mb-0">Reggeli: {{ $meal->wednessday_breakfast }}</p>
                            <p class="ml-3 mb-0">Ebéd: {{ $meal->wednessday_lunch }}</p>
                            <p class="ml-3 mb-0">Uzsonna: {{ $meal->wednessday_dinner }}</p>
                            <hr>
                            <h5>Csütörtök:</h5>
                            <p class="ml-3 mb-0">Reggeli: {{ $meal->thursday_breakfast }}</p>
                            <p class="ml-3 mb-0">Ebéd: {{ $meal->thursday_lunch }}</p>
                            <p class="ml-3 mb-0">Uzsonna: {{ $meal->thursday_dinner }}</p>
                            <hr>
                            <h5>Péntek:</h5>
                            <p class="ml-3 mb-0">Reggeli: {{ $meal->friday_breakfast }}</p>
                            <p class="ml-3 mb-0">Ebéd: {{ $meal->friday_lunch }}</p>
                            <p class="ml-3 mb-0">Uzsonna: {{ $meal->friday_dinner }}</p>
                            <hr>
                        </div>
                    </div>
                @endforeach
            @else
                <h5>Nincs még menu felvéve.</h5>
            @endif

        </div>

    </div>
@endsection