routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/test', 'HomeController@test')->name('test');

Route::get('/', 'GuestController@index')->name('index');
Route::get('/home', 'HomeController@index')->name('home');

//Teacher
Route::get('/teacher', 'TeacherController@index')->name('teacher');
Route::get('/teacher/register', 'TeacherController@register')->name('teacher.register');
Route::delete('/teacher/delete/{id}', 'TeacherController@destroy')->name('teacher.destroy');

Route::get('/profile', 'ProfileController@edit')->name('profile');
Route::post('/profile', 'ProfileController@update');
Route::resource('/news', 'NewsController');
Route::post('/child/confirm/{id}', 'GroupController@addChildren')->name('child.confirm');
Route::delete('/child/remove', 'GroupController@removeChildren')->name('child.remove');
Route::resource('/child', 'ChildController');
Route::resource('/group', 'GroupController');
Route::resource('/plan', 'PlanController');
Route::resource('/meal', 'MealController');
Route::resource('/product', 'ProductController');
Route::resource('/message', 'MessageController', ['only' => ['store', 'destroy']]);
Route::get('/diary', 'DiaryController@index')->name('diary.home');
Route::resource('/absence', 'AbsenceController');

Route::get('/cart', 'CartController@index');
Route::post('cart/add', 'CartController@add')->name('cart.add');
Route::delete('cart/{id}/delete', 'CartController@destroy')->name('cart.destroy');
Route::delete('cart/delete/all', 'CartController@deleteAll')->name('cart.destroy.all');
Route::post('/checkout', 'OrderController@checkout')->name('checkout');
Route::get('/payment-success', 'OrderController@paymentSuccess')->name('payment.success');
Route::get('/invoice', 'OrderController@invoice')->name('invoice');
Route::delete('subscription/stop/{id}', 'ProductController@stopSubscription')->name('subscription.stop');

app/Plan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Plan extends Model {

}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Plan;

class PlanController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    public function create() {
        return view('teacher.plan.create');
    }

    public function store(Request $request) {
        $this->validate($request, [
            'week' => 'required',
            'body' => 'required'
        ]);

        $plan = new Plan;
        $plan->week = $request->input('week');
        $plan->body = $request->input('body');
        $plan->group_id = $request->input('group_id');
        $plan->save();

        return redirect()->route('diary.home');
    }

    public function edit($id) {
        return view('teacher.plan.edit')->withPlan(Plan::find($id));
    }

    public function update(Request $request, $id) {
        $this->validate($request, [
            'week' => 'required',
            'body' => 'required'
        ]);

        $plan = Plan::find($id);
        $plan->week = $request->input('week');
        $plan->body = $request->input('body');
        $plan->group_id = $request->input('group_id');
        $plan->save();
        return redirect()->route('diary.home');
    }

    public function destroy($id) {
        $plan = Plan::find($id);
        $plan->delete();
        return redirect()->route('diary.home');
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class TeacherController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $teachers = User::where('type', 0)
                            ->orderBy('id', 'DESC')->paginate(30);


        return view('user.teacher.index')->withTeachers($teachers);;
    }

    public function register() {
        return view('user.teacher.register');
    }

    public function destroy($id) {
        $user = User::find($id);
        $user->delete();
        return redirect()->route('teacher');
    }

}

resources/views/teacher/plan/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <div class="card">
                <div class="card-header">Terv létrehozása</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('plan.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="week" class="col-md-2 col-form-label text-md-right">Hét sorszáma</label>

                            <div class="col-md-6">
                                <input id="week" type="number" class="form-control @error('week') is-invalid @enderror" name="week" value="{{ old('week') }}" autocomplete="title" autofocus required>

                                @error('week')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="body" class="col-md-2 col-form-label text-md-right">Terv</label>

                            <div class="col-md-6">
                                <textarea id="body" type="text" class="form-control @error('body') is-invalid @enderror" name="body" value="{{ old('body') }}" autocomplete="title" autofocus required></textarea>

                                @error('body')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <input type="hidden" name="group_id" value="{{ request()->get('group_id') }}">

                        <div class="form-group row justify-content-center text-center mt-3 mb-0">
                            <button type="submit" class="btn btn-primary" id="btn-save">Mentés</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/teacher/plan/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <div class="card">
                <div class="card-header">Hír szerkesztése</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('plan.update', $plan->id) }}">
                        @csrf
                        {{ method_field("PUT") }}

                        <div class="form-group row">
                            <label for="week" class="col-md-2 col-form-label text-md-right">Hét sorszáma</label>

                            <div class="col-md-6">
                                <input id="week" type="number" class="form-control @error('week') is-invalid @enderror" name="week" value="{{ $plan->week }}" autocomplete="title" autofocus required>

                                @error('week')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="body" class="col-md-2 col-form-label text-md-right">Terv</label>

                            <div class="col-md-6">
                                <textarea id="body" type="text" class="form-control @error('body') is-invalid @enderror" name="body" value="{{ $plan->body }}" autocomplete="title" autofocus required>{{ $plan->body }}</textarea>

                                @error('body')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <input type="hidden" name="group_id" value="{{ $plan->group_id}}">

                        <div class="form-group row justify-content-center text-center mt-3 mb-0">
                            <button type="submit" class="btn btn-primary" id="btn-save">Mentés</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection