routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/test', 'HomeController@test')->name('test');

Route::get('/', 'GuestController@index')->name('index');
Route::get('/home', 'HomeController@index')->name('home');

//Teacher
Route::get('/teacher', 'TeacherController@index')->name('teacher');
Route::get('/teacher/register', 'TeacherController@register')->name('teacher.register');
Route::delete('/teacher/delete/{id}', 'TeacherController@destroy')->name('teacher.destroy');

Route::get('/profile', 'ProfileController@edit')->name('profile');
Route::post('/profile', 'ProfileController@update');
Route::resource('/news', 'NewsController');
Route::post('/child/confirm/{id}', 'GroupController@addChildren')->name('child.confirm');
Route::delete('/child/remove', 'GroupController@removeChildren')->name('child.remove');
Route::resource('/child', 'ChildController');
Route::resource('/group', 'GroupController');
Route::resource('/plan', 'PlanController');
Route::resource('/meal', 'MealController');
Route::resource('/product', 'ProductController');
Route::resource('/message', 'MessageController', ['only' => ['store', 'destroy']]);
Route::get('/diary', 'DiaryController@index')->name('diary.home');
Route::resource('/absence', 'AbsenceController');

Route::get('/cart', 'CartController@index');
Route::post('cart/add', 'CartController@add')->name('cart.add');
Route::delete('cart/{id}/delete', 'CartController@destroy')->name('cart.destroy');
Route::delete('cart/delete/all', 'CartController@deleteAll')->name('cart.destroy.all');
Route::post('/checkout', 'OrderController@checkout')->name('checkout');
Route::get('/payment-success', 'OrderController@paymentSuccess')->name('payment.success');
Route::get('/invoice', 'OrderController@invoice')->name('invoice');
Route::delete('subscription/stop/{id}', 'ProductController@stopSubscription')->name('subscription.stop');

app/Child.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Child extends Model {

}

app/Http/Controllers/ChildController.php
<?php

namespace App\Http\Controllers;

use App\Absence;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Child;
use App\Group;
use App\Message;
use App\Product;
use App\Subscription;
use App\User;
use Carbon\Carbon;

class ChildController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $children = Child::orderBy('id', 'DESC')->paginate(30);

        foreach ($children as $child) {
            if ($child->is_confirmed == 1) {
                $group = Group::find($child->group_id);
                $child->group = $group->name ?? "Folyamatban";
            } else {
                $child->group = "Folyamatban";
            }
        }

        return view('user.child.index')->withChildren($children);
    }

    public function show($id) {
        $child = Child::find($id);

        $group = Group::where('id', $child->group_id)->first();
        $child->group_name = $group->name ?? "Nincs";

        $child->messages = Message::where('child_id', $child->id)
                                    ->orderBy('created_at', 'ASC')
                                    ->get();

        $from = Carbon::createFromFormat('Y-m-d', $child->birthday);
        $to = Carbon::now()->addMonth();
        $child->months = $to->diffInMonths($from);

        $child->absences = Absence::where('child_id', $child->id)
            ->orderBy('end', 'DESC')
            ->get();

        $lastBaseSubscription = Subscription::where('child_id', $child->id)
            ->where('type', 0)
            ->orderBy('valid_until', 'DESC')->first();

        if ($lastBaseSubscription) {
            $lastValidSubDate = Carbon::createFromFormat('Y-m-d', $lastBaseSubscription->valid_until);
            $now = Carbon::now();
            if (!$now->gt($lastValidSubDate)) {
                $child->base_subscription_until = $lastValidSubDate->toDateString();
            }
        }

        $specialSubscriptions = Subscription::where('child_id', $child->id)
            ->where('type', 1)
            ->orderBy('valid_until', 'DESC')->get();

        $activeSpecialSubscriptions = [];
        $inactiveSpecialSubscriptions = [];
        foreach ($specialSubscriptions as $sub) {
            $subDate = Carbon::createFromFormat('Y-m-d', $sub->valid_until);
            $sub->product = Product::where('id', $sub->product_id)->first()->title;
            $now = Carbon::now();
            if ($now->gt($subDate)) {
                $inactiveSpecialSubscriptions[] = $sub;
            } else {
                $activeSpecialSubscriptions[] = $sub;
            }
        }

        if (Auth::user()->type == 0) {
            $child->parent = User::where('id', $child->parent_id)->first();
            return view('teacher.child.show')
                ->withChild($child)
                ->withActiveSpecialSubscriptions($activeSpecialSubscriptions)
                ->withInactiveSpecialSubscriptions($inactiveSpecialSubscriptions);;
        }

        if (Auth::user()->type == 1) {
            if (isset($group->teacher_id)) {
                if ($group->teacher_id != 0 && $group->teacher_id != -1) {
                    $child->teacher = User::where('id', $group->teacher_id)->first();
                }
            }
            return view('user.child.show')
                ->withChild($child)
                ->withActiveSpecialSubscriptions($activeSpecialSubscriptions)
                ->withInactiveSpecialSubscriptions($inactiveSpecialSubscriptions);
        }
    }

    public function create() {
        return view('user.child.create');
    }

    public function store(Request $request) {
        $this->validate($request, [
            'child_name' => 'required'
        ]);

        $child = new Child;
        $child->child_name = $request->input('child_name');
        $child->sensitivity = $request->input('sensitivity');
        $child->base_disease = $request->input('base_disease');
        $child->birthday = $request->input('birthday');
        $child->parent_id = Auth::user()->id;
        $child->save();

        return redirect()->route('child.index');
    }

    public function edit($id) {
        return view('user.child.edit')->withChild(Child::find($id));
    }

    public function update(Request $request, $id) {
        $this->validate($request, [
            'child_name' => 'required'
        ]);

        $child = Child::find($id);
        $child->child_name = $request->input('child_name');
        $child->sensitivity = $request->input('sensitivity');
        $child->base_disease = $request->input('base_disease');
        $child->save();

        return redirect()->route('child.index');
    }

    public function destroy($id) {
        $child = Child::find($id);
        $child->delete();
        return redirect()->route('child.index');
    }

}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class TeacherController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $teachers = User::where('type', 0)
                            ->orderBy('id', 'DESC')->paginate(30);


        return view('user.teacher.index')->withTeachers($teachers);;
    }

    public function register() {
        return view('user.teacher.register');
    }

    public function destroy($id) {
        $user = User::find($id);
        $user->delete();
        return redirect()->route('teacher');
    }

}

resources/views/teacher/child/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container pb-4 mt-3">

        <div class="row justify-content-between mb-3">
            <a href="/{{ app('request')->input('from') }}" class="btn btn-primary">Vissza</a>
            @if(isset($child->base_subscription_until))
            <span class="text-success">
                Bölcsödei alapdíj befizetve eddig: {{ $child->base_subscription_until }}.
            </span>
            @else
            <span class="text-danger">
                Bölcsödei alapdíjja nincs befizetve!
            </span>
            @endif
        </div>

        <div class="row justify-content-between mb-4">

            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h4 class="mb-0">{{ $child->child_name }}</h4>
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">{{ $child->group_name }}</h5>

                      <p class="card-text mb-0">Érzékenység:</p>
                      <p class="ml-3">{{ $child->sensitivity }}</p>

                      <p class="card-text mb-0">Alapbetegség:</p>
                      <p class="ml-3">{{ $child->base_disease }}</p>

                      <p class="card-text mb-0">Kor:</p>
                      <p class="ml-3">{{ $child->months }} hónapos</p>

                      <p class="card-text mb-0">Szülő adatai:</p>
                      <p class="ml-3 mb-0">{{ $child->parent->parent_name }}</p>
                      <p class="ml-3 mb-0">{{ $child->parent->phone }}</p>
                      <p class="ml-3 mb-0">{{ $child->parent->email }}</p>
                    </div>
                  </div>
            </div>

            <div class="col-6">
                <div class="card">
                    <div class="d-flex card-header justify-content-between">
                        <h4 class="mb-0">Hiányzások</h4>
                    </div>
                    <div class="card-body" style="max-height: 350px;overflow-y: scroll;">
                        @if (count($child->absences) > 0)
                            @foreach ($child->absences as $absence)
                            <div class="row">
                                    <div class="col-10">
                                        <p class="mb-0">({{ $absence->start }}) - ({{ $absence->end }})</p>
                                        <p class="mb-0">Ok: <br> {{ $absence->cause }}</p>
                                    </div>
                                    <div class="d-flex col-2 align-items-center">
                                        <div class="w-100">
                                            <form action="{{ route('absence.destroy', $absence->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{method_field('DELETE')}}
                                                <button onclick="return confirm('Biztos, hogy törölni szeretnéd a hiányzást?');" type="submit" class="btn btn-danger mr-1"><i class="fas fa-trash"></i></button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <hr class="mt-1">
                            @endforeach
                        @else
                            <h5>Nincs még hiányzása.</h5>
                        @endif
                    </div>
                </div>
            </div>

        </div>

        <div class="row justify-content-center pb-5">
            <div class="col-8">
                <div class="card">
                    <div class="d-flex card-header justify-content-between">
                        <h4 class="mb-0">Megjegyzések</h4>
                    </div>
                    <div id="message-container" class="card-body" style="min-height: 400px; max-height: 600px;overflow-y: scroll;">

                        @if(count($child->messages))
                            @foreach ($child->messages as $message)
                            <div class="card bg-primary mb-3 text-white">
                                <div class="card-body pt-3 pb-1">
                                    <div class="row mx-0">
                                        <div class="col-11">{{ $message->message }}</div>
                                        <div class="row col-1 mx-0 px-0 justify-content-end">
                                            <form action="{{ route('message.destroy', $message->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{method_field('DELETE')}}
                                                <button onclick="return confirm('Biztos, hogy törölni szeretnéd a megjegyzést?');" type="submit" class="btn btn-danger mr-1"><i class="fas fa-trash"></i></button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="row justify-content-end">
                                        <span class="text-message-date">
                                            {{ $message->created_at }}
                                        </span>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        @else
                            <h5>
                                Még nincs felvéve megjegyzés.
                            </h5>
                        @endif

                    </div>
                    <div class="card-footer">

                        <form action="{{ route('message.store') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group mb-2">
                                <textarea class="form-control" id="message" name="message" rows="3"></textarea>
                            </div>
                            <input type="hidden" name="child_id" value="{{ $child->id }}">
                            <div class="row justify-content-center">
                                <button type="submit" class="btn btn-primary" style="min-width: 150px;">Küldés</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-between mb-3">
            <div class="col-6">
                <div class="card" style="">
                    <div class="card-header">
                      Aktív egyéb szolgáltatások
                    </div>
                    <div style="max-height: 250px;overflow-y: scroll">
                        @if (count($activeSpecialSubscriptions) > 0)
                        <ul class="list-group list-group-flush">
                            @foreach ($activeSpecialSubscriptions as $sub)
                                <li class="list-group-item">{{ $sub->product }} | <span class="text-success">eddig: {{ $sub->valid_until }}</span></li>
                            @endforeach
                        </ul>
                        @else
                        <p class="m-3">
                            Nincs aktív egyéb szolgáltatás.
                        </p>
                        @endif
                    </div>
                </div>
            </div>

            <div class="col-6">
                <div class="card" style="">
                    <div class="card-header">
                      Lejárt egyáb szolgáltatások
                    </div>
                    <div style="max-height: 300px;overflow-y: scroll">
                        @if (count($inactiveSpecialSubscriptions) > 0)
                        <ul class="list-group list-group-flush">
                            @foreach ($inactiveSpecialSubscriptions as $sub)
                                <li class="list-group-item">{{ $sub->product }} | <span class="text-danger">lejárt ekkor: {{ $sub->valid_until }}</span></li>
                            @endforeach
                        </ul>
                        @else
                            <p class="m-3">Nincs lejárt egyéb szolgáltatás.</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>

    </div>


    <script>

        document.addEventListener("DOMContentLoaded", function(){
            const element = document.getElementById("message-container");
            element.scrollTop = element.scrollHeight;
        });

    </script>

@endsection