routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/test', 'HomeController@test')->name('test');

Route::get('/', 'GuestController@index')->name('index');
Route::get('/home', 'HomeController@index')->name('home');

//Teacher
Route::get('/teacher', 'TeacherController@index')->name('teacher');
Route::get('/teacher/register', 'TeacherController@register')->name('teacher.register');
Route::delete('/teacher/delete/{id}', 'TeacherController@destroy')->name('teacher.destroy');

Route::get('/profile', 'ProfileController@edit')->name('profile');
Route::post('/profile', 'ProfileController@update');
Route::resource('/news', 'NewsController');
Route::post('/child/confirm/{id}', 'GroupController@addChildren')->name('child.confirm');
Route::delete('/child/remove', 'GroupController@removeChildren')->name('child.remove');
Route::resource('/child', 'ChildController');
Route::resource('/group', 'GroupController');
Route::resource('/plan', 'PlanController');
Route::resource('/meal', 'MealController');
Route::resource('/product', 'ProductController');
Route::resource('/message', 'MessageController', ['only' => ['store', 'destroy']]);
Route::get('/diary', 'DiaryController@index')->name('diary.home');
Route::resource('/absence', 'AbsenceController');

Route::get('/cart', 'CartController@index');
Route::post('cart/add', 'CartController@add')->name('cart.add');
Route::delete('cart/{id}/delete', 'CartController@destroy')->name('cart.destroy');
Route::delete('cart/delete/all', 'CartController@deleteAll')->name('cart.destroy.all');
Route::post('/checkout', 'OrderController@checkout')->name('checkout');
Route::get('/payment-success', 'OrderController@paymentSuccess')->name('payment.success');
Route::get('/invoice', 'OrderController@invoice')->name('invoice');
Route::delete('subscription/stop/{id}', 'ProductController@stopSubscription')->name('subscription.stop');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model {

}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use App\News;

class NewsController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $news = News::orderBy('id', 'DESC')->paginate(30);

        return view('teacher.news.index')->withNewsList($news);
    }

    public function create() {
        return view('teacher.news.create');
    }

    public function store(Request $request) {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required'
        ]);

        $news = new News;
        $news->title = $request->input('title');
        $news->description = $request->input('description');
        $news->creator = Auth::user()->parent_name;
        $news->save();

        return redirect()->route('news.index');
    }

    public function edit($id) {
        return view('teacher.news.edit')->withNews(News::find($id));
    }

    public function update(Request $request, $id) {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required'
        ]);

        $news = News::find($id);
        $news->title = $request->input('title');
        $news->description = $request->input('description');
        $news->save();
        return redirect()->route('news.index');
    }

    public function destroy($id) {
        $news = News::find($id);
        $news->delete();
        return redirect()->route('news.index');
    }

}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class TeacherController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $teachers = User::where('type', 0)
                            ->orderBy('id', 'DESC')->paginate(30);


        return view('user.teacher.index')->withTeachers($teachers);;
    }

    public function register() {
        return view('user.teacher.register');
    }

    public function destroy($id) {
        $user = User::find($id);
        $user->delete();
        return redirect()->route('teacher');
    }

}

resources/views/teacher/news/create.blade.php
@extends('layouts.app')

@section('styles')
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
@endsection

@section('content')
<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <div class="card">
                <div class="card-header">Hír létrehozása</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('news.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-2 col-form-label text-md-right">Cím*</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" autocomplete="title" placeholder="Cím" autofocus required>

                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="">
                            <label class="mb-0 col-form-label">Szöveg törzs:</label>
                            <textarea id="summernote" name="description"></textarea>
                        </div>

                        <div class="form-group row justify-content-center text-center mt-3 mb-0">
                            <button type="submit" class="btn btn-primary" id="btn-save">Mentés</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('#summernote').summernote({
        placeholder: '',
        tabsize: 2,
        height: 120,
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
        ]
      });
</script>

@endsection

resources/views/teacher/news/edit.blade.php
@extends('layouts.app')

@section('styles')
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
@endsection

@section('content')
<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <div class="card">
                <div class="card-header">Hír szerkesztése</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('news.update', $news->id) }}">
                        @csrf
                        {{ method_field("PUT") }}
                        <div class="form-group row">
                            <label for="title" class="col-md-2 col-form-label text-md-right">Cím*</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $news->title }}" autocomplete="title" placeholder="Cím" autofocus required>

                                @error('parent_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="">
                            <label class="mb-0 col-form-label">Szöveg törzs:</label>
                            <textarea id="summernote" name="description">
                                {!! $news->description !!}
                            </textarea>
                        </div>

                        <div class="form-group row justify-content-center text-center mt-3 mb-0">
                            <button type="submit" class="btn btn-primary" id="btn-save">Mentés</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('#summernote').summernote({
        placeholder: '',
        tabsize: 2,
        height: 120,
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
        ]
      });
</script>

@endsection

resources/views/teacher/news/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-12 col-md-8 mt-2">
        <h2>Hírek</h2>

        <a href="{{ route('news.create') }}" class="btn btn-warning float-right mb-1">Új hír</a>

        @if(count($newsList) > 0)
            <table class="table table-bordered">
                <tr>
                    <td>Cím</td>
                    <td>Szerző</td>
                    <td>Szöveg</td>
                </tr>
                @foreach($newsList as $news)
                    <tr>
                        <td>{{ $news->title }}</td>
                        <td>{{ $news->creator }}</td>
                        <td>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
                                Megtekintés
                            </button>
                            <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">{{ $news->title }}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                    <div class="modal-body">
                                        {!! $news->description !!}
                                    </div>
                                </div>
                                </div>
                            </div>
                        </td>
                        <td class="row mx-0 justify-content-center">
                            <a href="{{ route('news.edit', $news->id) }}" class="btn btn-primary float-right mr-1 mb-1">Szerkesztés</a>
                            <form action="{{ route('news.destroy', $news->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{method_field('DELETE')}}
                                <button onclick="return confirm('Biztos, hogy törölni szeretnéd a {{ $news->title }} című hírt?');" type="submit" class="btn btn-danger mr-1">Törlés</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </table>

            @if(count($newsList) > 0)
                <div class="pagination">
                    <?php echo $newsList->render();  ?>
                </div>
            @endif

        @else
            <i>Nincs még hír felvéve</i>
        @endif

    </div>
</div>

@endsection